### ISSUE TITLE
Trying to use top.js on a hosted Ghost

### ISSUE THREAD

**Issue by calvinpark** [conwid/GhostHelpers#1]
Thanks for the great tool and the tutorial.
I'm at this stage
> Set the GA_CLIENT_EMAIL environment variable to the value of "client_email", and the GA_PRIVAT_KEY environment variable to the value of "private_key" from the previous step. You'll need the viewId when actually using the helper, as shown in the Examples section.

I'm using Ghost(Pro) which means ghost.org manages the server. As such, I don't think I have an access to the environment variables.

Do you see any other way I can use `top.js`? I understand that these are secrets therefore can't be baked into the js.

Thank you

**Comment by conwid** [comment]
Actually (while it is definitely not an elegant or scalable solution), you can bake it into the js. The helpers run on server side and not downloaded to the client, so there are no security risks.
Also thanks for copying the quoted segment, the name of the environment variable should be GA_PRIVATE_KEY (I corrected the documentation).

**Comment by calvinpark** [comment]
Got it thank you. I'm asking Ghost support on whether I can add a server side helper to a managed service.
